config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  root 'dashboard#index'
  get 'home/index'
  get 'room/show'

  resources :friendships, only: [:create, :destroy, :update]
  resources :posts do 
    resources :likes, only: [:create, :destroy]
  	resources :comments do
      resources :likes, only: [:create, :destroy]
      member do 
        get 'view'
      end
    end
  end

  resources :profiles do 
    collection do 
      get 'current_user_friends'
      post 'search_user'
    end
  end

  resources :conversations, only: [] do
    resources :messages , only: [] do 
      collection do 
        get :create 
      end      
    end 
    member do get :close end

    collection do get :open end
  end
  
  devise_for :users, controllers: {registrations: 'registrations'}

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_many :likes, as: :likeable
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

  validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
	
	after_create_commit { NotificationBroadcastJob.perform_later(self) }  
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :imageable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes, as: :likeable
  has_many :pictures, as: :imageable

  accepts_nested_attributes_for :pictures
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :notifications
  has_many :messages
  has_many :conversations, foreign_key: :sender_id
  has_many :pictures, as: :imageable
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: :friend_id
  has_many :inverse_friends, through: :inverse_friendships, source: :user  


  after_create :signup_confirmation

  def signup_confirmation
  UserMailer.with(user: self).signup_confirmation.deliver_later
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_post, only: [:edit, :create, :update, :destroy]
  before_action :get_comment, only: [:show, :edit, :update, :destroy]

  def new
    @comment = Comment.new
  end

  def create
    binding.pry
    @comment = @post.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to root_path, notice: 'Comment was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_path(@post), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def get_comment
    @comment = get_post.find_by(id: params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content).merge({user_id: current_user.id, commentor_name: current_user.first_name})
  end

  def get_post
    @post = current_user.posts.find_by(id: params[:post_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    self.per_form_csrf_tokens = true
    session[:conversations] ||= []

    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])  
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :get_post, only: [:create, :destroy]

  def create
    @like = @post.likes.new(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to root_path, notice: 'like was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def destroy    
    @post.likes.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Like destroyed.' }
      format.js
    end
  end

private

  def get_post 
    @post = Post.find_by(id: params[:post_id])
  end
  def like_params
    params.permit().merge(user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_post, only: [:show, :edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def get_post
    @post = current_user.posts.find_by(id: params[:id])
  end

  def post_params
    params.require(:post).permit(:content, pictures_attributes: [:avatar])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model:[ post, post.comments.build ], remote: true) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="actions">
    <%= form.text_field :content, placeholder: "comment here......", class: "form-control col-sm-5", id: "ctext_field#{post.id}" %><br>
  </div>
<% end %>

app/views/comments/_show_post_comments.html.erb
<p>
  <% if comment.id %>
    <strong><%= comment.commentor_name %> :</strong>
    <%= comment.content %><br>
    <a href="#"><i class="glyphicon glyphicon-thumbs-up"></i> Like</a>
    <a href="# "><i class="glyphicon glyphicon-comment"></i> Reply</a>      
  <% end %>
</p>

app/views/comments/create.js.erb
$('#ctext_field<%= @post.id %>').val("")
$('.comments<%= @post.id%>').append("<%= j render :partial => 'comments/show_post_comments', locals: { :comment => @comment } %>");

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/view.html.erb
<%= @comment.content %>