config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  root 'dashboard#index'
  get 'home/index'
  get 'room/show'

  resources :friendships, only: [:create, :destroy, :update]
  resources :posts do 
    resources :likes, only: [:create, :destroy]
  	resources :comments do
      resources :likes, only: [:create, :destroy]
      member do 
        get 'view'
      end
    end
  end

  resources :profiles do 
    collection do 
      get 'current_user_friends'
      post 'search_user'
    end
  end

  resources :conversations, only: [] do
    resources :messages , only: [] do 
      collection do 
        get :create 
      end      
    end 
    member do get :close end

    collection do get :open end
  end
  
  devise_for :users, controllers: {registrations: 'registrations'}

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_many :likes, as: :likeable
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

  validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
	
	after_create_commit { NotificationBroadcastJob.perform_later(self) }  
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :imageable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes, as: :likeable
  has_many :pictures, as: :imageable

  accepts_nested_attributes_for :pictures
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :notifications
  has_many :messages
  has_many :conversations, foreign_key: :sender_id
  has_many :pictures, as: :imageable
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: :friend_id
  has_many :inverse_friends, through: :inverse_friendships, source: :user  


  after_create :signup_confirmation

  def signup_confirmation
  UserMailer.with(user: self).signup_confirmation.deliver_later
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    self.per_form_csrf_tokens = true
    session[:conversations] ||= []

    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/partials/_create_post.html.erb
<div class="container">
  <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-body">
                <section class="post-heading">
                    <div class="row">
                        <div class="col-md-11">
                            <div class="media">
                              <div class="media-left">
                                <a href="#">
                                  <img class="media-object photo-profile" src="/assets/faces/face1.jpg" width="40" height="40" alt="...">
                                </a>
                              </div>
                              <div class="media-body">
                                <a href="#" class="anchor-username"><h4 class="media-heading"><%= current_user.first_name %></h4></a> 
                                <a href="#" class="anchor-time">51 mins</a>
                              </div>
                            </div>
                        </div>
                         <div class="col-md-1">
                             <a href="#"><i class="glyphicon glyphicon-chevron-down"></i></a>
                         </div>
                    </div>             
                </section>
                <div class="panel panel-default">
                  <div id="collapse0" class="panel-collapse collapse">
                    <%= render "posts/form", locals: {post: @post} %>
                  </div>
                </div>
                <h4 class="panel-title">
                  <button data-toggle="collapse" href="#collapse0" class="btn btn-primary">Open Post Form</button>
                </h4>
            </div>
        </div>   
  </div>
</div>

app/views/partials/_footer.html.erb
<footer class="footer">
  <div class="container-fluid clearfix">
    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2018
      <a href="http://www.bootstrapdash.com/" target="_blank">Bootstrapdash</a>. All rights reserved.</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with
      <i class="mdi mdi-heart text-danger"></i>
    </span>
  </div>
</footer>

app/views/partials/_header.html.erb
<div>  
  <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
      <a class="navbar-brand brand-logo" href="index.html">
        <img src="/assets/logo.svg" alt="logo" />
      </a>
      <a class="navbar-brand brand-logo-mini" href="index.html">
        <img src="/assets/logo-mini.svg" alt="logo" />
      </a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center">
      <ul class="navbar-nav navbar-nav-left">
        <%= form_tag(search_user_profiles_path, method: :post) do %>
        <%= search_field_tag 'search', nil, style: "color: black" %>
        <% end %>
      </ul>

      
      <ul class="nav navbar-nav navbar-nav-right">
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
              <i class="mdi mdi-bell"></i>
              <!-- <span class="count">4</span> -->
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown" id="notifications-id">
                <%if @notifications.presence %>
                  <% @notifications.each do |notification| %>
                    <%= render partial: 'notifications/notification', locals: {notification: notification}%>
                  <% end %>
                <% end %>
              </div>
            </a>
          </li>
          <li class="nav-item dropdown d-none d-xl-inline-block">
            <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
              <span class="profile-text">Hello, <%= current_user.first_name %> !</span>
              <img class="img-xs rounded-circle" src="/assets/faces/face1.jpg" alt="Profile image">
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
              <a class="dropdown-item p-0">
                <div class="d-flex border-bottom">
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                    <i class="mdi mdi-bookmark-plus-outline mr-0 text-gray"></i>
                  </div>
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center border-left border-right">
                    <i class="mdi mdi-account-outline mr-0 text-gray"></i>
                  </div>
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                    <i class="mdi mdi-alarm-check mr-0 text-gray"></i>
                  </div>
                </div>
              </a>
              <a class="dropdown-item mt-2">
                Manage Accounts
              </a>
              <a class="dropdown-item">
                Change Password
              </a>
              <a class="dropdown-item">
                Check Inbox
              </a>
              <a class="dropdown-item">
                <div class="form-group login-button">
                  <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
                </div>
              </a>
            </div>
          </li>
        <% else %>
          <% if params[:controller] == "registrations" %>
            <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
              <div class="form-inline" id="sessions-form">    

                <div class="form-group">
                  <%= f.email_field :email, class: "form-control form-half", autocomplete: "email", placeholder: "Email" %>
                </div>
                <div class="form-group">
                  <%= f.password_field :password, class: "form-control form-half", autocomplete: "current-password", placeholder: "Password" %>
                </div>
                <div class="form-group login-button">
                  <%= f.submit "Log in", class: "btn btn-danger" -%>
                </div>
              </div>
            <% end %>
          <% else %>
            <div class="form-group login-button">
              <%= button_to "Sign Up", new_user_registration_path, method: :get, class: "btn btn-danger" %>
            </div>
          <% end %>
        <% end %>
      </ul>

      <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
        <span class="mdi mdi-menu"></span>
      </button>
    </div>
  </nav>
</div>
<div>
  <% if not current_user %>
    <%= yield %> 
  <% end %>
</div>

app/views/partials/_show_all_post.html.erb
<% @posts.each do |post| %>
  <div class="container">
    <div class="col-md-10 ">
          <div class="panel panel-default">
              <div class="panel-body">
                 <section class="post-heading">
                      <div class="row">
                          <div class="col-md-11">
                              <div class="media">
                                <div class="media-left">
                                  <a href="#">
                                    <img class="media-object photo-profile" src="/assets/faces/face1.jpg" width="40" height="40" alt="...">
                                  </a>
                                </div>
                                <div class="media-body">
                                  <a href="#" class="anchor-username"><h4 class="media-heading"><%= current_user.first_name %></h4></a> 
                                  <a href="#" class="anchor-time">51 mins</a>
                                </div>
                              </div>
                          </div>
                           <div class="col-md-1">
                               <a href="#"><i class="glyphicon glyphicon-chevron-down"></i></a>
                           </div>
                      </div>             
                 </section>
                 <section class="post-body">
                    
                 </section>
                 <section class="post-footer">
                     <hr>
                     <div class="post-footer-option container">
                          <ul class="list-unstyled">
                              <li><a href="#"><i class="glyphicon glyphicon-thumbs-up"></i> Like</a></li>
                              <li><a href="#"><i class="glyphicon glyphicon-comment"></i> Comment</a></li>
                              <li><a href="#"><i class="glyphicon glyphicon-share-alt"></i> Share</a></li>
                          </ul>
                     </div>
                 </section>
              </div>
          </div>   
    </div>
  </div>
<% end %>

app/views/partials/_sidebar.html.erb
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">
    <li class="nav-item nav-profile">
      <div class="nav-link">
        <div class="user-wrapper">
          <div class="profile-image">
            <img src="/assets/faces/face1.jpg" alt="profile image">
          </div>
          <div class="text-wrapper">
            <p class="profile-name">Richard V.Welsh</p>
            <div>
              <small class="designation text-muted">Manager</small>
              <span class="status-indicator online"></span>
            </div>
          </div>
        </div>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/">
        <i class="menu-icon mdi mdi-television"></i>
        <span class="menu-title">Dashboard</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="index.html">
        <i class="menu-icon mdi mdi-television"></i>
        <span class="menu-title">Profile</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="/profiles">
        <i class="menu-icon mdi mdi-television"></i>
        <span class="menu-title">All Users</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="/profiles/current_user_friends">
        <i class="menu-icon mdi mdi-television"></i>
        <span class="menu-title">Friends</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="index.html">
        <i class="menu-icon mdi mdi-television"></i>
        <span class="menu-title">Friend Requests</span>
      </a>
    </li>
  </ul>
</nav>