config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  root 'dashboard#index'
  get 'home/index'
  get 'room/show'

  resources :friendships, only: [:create, :destroy, :update]
  resources :posts do 
    resources :likes, only: [:create, :destroy]
  	resources :comments do
      resources :likes, only: [:create, :destroy]
      member do 
        get 'view'
      end
    end
  end

  resources :profiles do 
    collection do 
      get 'current_user_friends'
      post 'search_user'
    end
  end

  resources :conversations, only: [] do
    resources :messages , only: [] do 
      collection do 
        get :create 
      end      
    end 
    member do get :close end

    collection do get :open end
  end
  
  devise_for :users, controllers: {registrations: 'registrations'}

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_many :likes, as: :likeable
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

  validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
	
	after_create_commit { NotificationBroadcastJob.perform_later(self) }  
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :imageable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes, as: :likeable
  has_many :pictures, as: :imageable

  accepts_nested_attributes_for :pictures
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :notifications
  has_many :messages
  has_many :conversations, foreign_key: :sender_id
  has_many :pictures, as: :imageable
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: :friend_id
  has_many :inverse_friends, through: :inverse_friendships, source: :user  


  after_create :signup_confirmation

  def signup_confirmation
  UserMailer.with(user: self).signup_confirmation.deliver_later
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    self.per_form_csrf_tokens = true
    session[:conversations] ||= []

    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])  
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :get_post, only: [:create, :destroy]

  def create
    @like = @post.likes.new(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to root_path, notice: 'like was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def destroy    
    @post.likes.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Like destroyed.' }
      format.js
    end
  end

private

  def get_post 
    @post = Post.find_by(id: params[:post_id])
  end
  def like_params
    params.permit().merge(user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_post, only: [:show, :edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def get_post
    @post = current_user.posts.find_by(id: params[:id])
  end

  def post_params
    params.require(:post).permit(:content, pictures_attributes: [:avatar])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @messages = Message.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/likes/create.js.erb
$('#like_count<%= @post.id %>').text("<%= j @post.likes.count.to_s %> likes")
$('.like<%= @post.id %>').html("<%= j (render partial: 'posts/like_unlike', locals: {like: @like, post: @post}) %>")

app/views/likes/destroy.js.erb
$('#like_count<%= @post.id %>').text("<%= j @post.likes.count.to_s %> likes")
$('.like<%= @post.id %>').html("<%= j (render partial: 'posts/like_unlike', locals: {like: @like, post: @post}) %>")

app/views/posts/_form.html.erb
<%= bootstrap_form_with(model: @post, remote: true, authenticity_token: true, class: "create_post") do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :content, class: "from-group", placeholder: "enter post caption...", label: "Caption"%>
    <div>
      <%= form.fields_for :pictures do |image_form| %>
        <%= image_form.file_field :avatar, label: "Upload Image"%>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Post', class: 'btn btn-primary', id: "create_post" %>
  </div>
<% end %>

app/views/posts/_like_unlike.html.erb
<% if @like.blank? %>
  <li>
    <%= button_to 'Like', post_likes_path(post.id), method: :post, remote: true, class: "btn btn-primary" %>
  </li>
<% else %>
  <li>
    <%= button_to 'UnLike', post_like_path(post.id, @like), method: :delete,remote: true, class: "btn btn-success" %>  
  </li>
<% end %>

app/views/posts/create.js.erb
$('.comments<%= @post.id%>').append("<%= render :template => "posts/index", locals: { :post => @post } %>");

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <div class="col-md-8 ">
      <div class="panel panel-default">
        <div class="panel-body">
          <section class="post-heading">
            <div class="row">
              <div class="col-md-11">
                <div class="media">
                  <div class="media-left">
                    <a href="#">
                      <img class="media-object photo-profile" src="/assets/faces/face1.jpg" width="40" height="40" alt="...">
                    </a>
                  </div>
                  <div class="media-body">
                    <a href="#" class="anchor-username"><h4 class="media-heading"><%= current_user.first_name %></h4></a> 
                    <a href="#" class="anchor-time">51 mins</a>
                  </div>
                </div>
              </div>
               <div class="col-md-1">
                   <a href="#"><i class="glyphicon glyphicon-chevron-down"></i></a>
               </div>
            </div>             
          </section>
          <section class="post-body">
            <%= post.content %>
            <%=image_tag(post.pictures.first.avatar.url) if post.pictures.present? %>
          </section>
          <section class="post-footer">
           <hr>
           <div class = "row" >
            <div class="post-footer-option container" >
           
              <ul class="list-unstyled">
                <div class="col-sm-4 ">
                  <% @like = @user_likes.where(likeable_id: post.id).find_by(user_id: current_user.id) %>
                  <p id="like_count<%= post.id %>">
                    <%= post.likes.count %> likes 
                  </p>           
                  <div class="like<%= post.id %>">
                    <%= render partial: "posts/like_unlike", locals: {like: @like, post: post} %>
                  </div>
                  
                </div>
                <div class="col-sm-4" >
                  <li><a data-toggle="collapse" href="#collapse<%= post.id %>" ><i class="glyphicon glyphicon-comment"></i> Comment</a></li>
                </div>
                <div class="col-sm-4">
                  <li><a href="#"><i class="glyphicon glyphicon-share-alt"></i> Share</a></li>
                </div>
              </ul>
            </div>
           </div>
          </section>
          <div id="collapse<%= post.id %>" class="panel-collapse collapse">
            <%= render :partial => 'comments/form', locals: { :post => post }%>
            <div class="comments<%= post.id %>">
              <% post.comments.each do |comment| %> 
              <%= render :partial => 'comments/show_post_comments', locals: { :comment => comment } %>  
              <% end %>
            </div>          
          </div>
        </div>
      </div>   
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% if @post %>
<p id="notice"><%= notice %></p>
  <p>
    <strong>Content:</strong>
    <%= @post.content %>
    <%=image_tag(@post.avatar.url) %>
  </p>

  <h2>Comments</h2>
  <% @post.comments.each do |comment| %> 
    <p>
      <strong>Comment:</strong>
      <%= comment.content %>
      <%= link_to 'Edit', edit_post_comment_path(@post, comment) %>
    </p>
  <% end %>
   
  <h2>Add a comment:</h2>
  <%= form_with(model: [ @post, @post.comments.build ], local: true, method: :post ) do |form| %>
    <p>
      <%= form.label :content %><br>
      <%= form.text_area :content %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>

  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>
<% else %>
  <a>Post id do not exist! <%= button_to "Posts", posts_path, method: :get, class: "btn btn-danger" %></a>
<% end %>